#FROM pytorch/pytorch:1.8.0-cuda11.1-cudnn8-devel
FROM nvidia/cuda:11.2.2-cudnn8-runtime-ubuntu18.04

# NOTE
# You need at least one ssh public key to access this container.
# keys need to be placed under "./copy/pub/" directory for copying

# install zsh curl wget git
RUN apt update && apt install build-essential git zsh wget curl ssh tmux python3-distutils python3-dev libgl1-mesa-glx -y && systemctl enable ssh.service

# install pip
RUN curl https://bootstrap.pypa.io/pip/3.6/get-pip.py -o get-pip.py && python3 get-pip.py


# install pip packages
COPY copy/requirements.txt /root/requirements.txt
RUN python3 -m pip install -r /root/requirements.txt

# ssh configuration
COPY copy/pub /root/pub
COPY copy/ssh_config.sh /root/ssh_config.sh
RUN chmod 755 /root/ssh_config.sh
RUN bash -c /root/ssh_config.sh

# copy jupyter configuration
COPY copy/.jupyter /root/.jupyter

# copy entry script
COPY copy/run.sh /root/run.sh
RUN chmod 755 /root/run.sh

EXPOSE 22
EXPOSE 8097
EXPOSE 8888
