FROM tensorflow/tensorflow:latest-gpu-jupyter

# need a ssh public key to access this container.
ARG SSH_KEY_PATH

# install zsh curl wget git
RUN apt update && apt install build-essential git zsh wget curl ssh tmux python3-distutils python3-dev libgl1-mesa-glx -y && systemctl enable ssh.service
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py

COPY copy/ /root/
RUN chmod 755 /root/run.sh

# install requirements
RUN python3 -m pip install -r /root/requirements.txt


# customize zsh with oh-my-zsh 
RUN wget https://raw.githubusercontent.com/ohilho/initialize_script/master/ohmyzsh/ohmyzsh.sh && /bin/bash ohmyzsh.sh

# copy ssh public key 
COPY $SSH_KEY_PATH ssh_key.pub
RUN mkdir -p /root/.ssh
RUN cat ssh_key.pub >> /root/.ssh/authorized_keys
RUN rm ssh_key.pub

EXPOSE 22
EXPOSE 8888
EXPOSE 6006
