version: "3"

services:
  jupyter:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    ports:
      - "8888:8888"
    volumes:
      - source:/tf # notebook dir
      - log:/tf/log
      - /media/ohilho/Data/dataset:/tf/dataset
    restart: always

  tensorboard:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    ports:
      - "6006:6006"
    command: 
      - tensorboard
      - --logdir=/tf/log
      - --port=6006
      - --host=0.0.0.0
    volumes:
      - source:/tf # notebook dir
      - log:/tf/log # notebook dir
    restart: always

volumes:
  source:
  log:

