FROM pytorch/pytorch:1.8.0-cuda11.1-cudnn8-devel

# install pytorch and visdom
RUN python3 -m pip install --no-cache-dir torch torchvision visdom

# install zsh curl wget git
RUN apt update && apt install git zsh wget curl -y
# customize zsh with oh-my-zsh 
RUN wget https://raw.githubusercontent.com/ohilho/initialize_script/master/ohmyzsh/ohmyzsh.sh && /bin/bash ohmyzsh.sh

# port open for visdom server
EXPOSE 8097
